name: Publish tag release

on:
  push:
    tags:
    - '[0-9]+\.[0-9]+\.[0-9]+' # Push events to matching semver 20.15.10

jobs:
  publish:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Get Release Version
      id: get_version
      run: VERSION=$(./gradlew currentVersion -q -Prelease.quiet) && echo ::set-output name=VERSION::$VERSION
    - name: Build with Gradle
      run: ./gradlew build
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          toolbelt/build/libs/toolbelt-*.jar
          toolbelt-groovy/build/libs/toolbelt-*.jar
          toolbelt-jewelcli/build/libs/toolbelt-*.jar
          toolbelt-json-jackson/build/libs/toolbelt-*.jar
          toolbelt-snakeyaml/build/libs/toolbelt-*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      fail_on_unmatched_files: true
